# Generated by Django 5.0.4 on 2024-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(verbose_name='1, 2, 3, 4, 5'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(verbose_name='1, 2, 3, 4, 5'),
        ),
    ]
