# Generated by Django 5.0.4 on 2024-04-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_alter_bugreport_priority_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreport',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='featurerequest',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4, 5)),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4, 5)),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('Consideration', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Рассмотрение', max_length=100),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
